GET http://localhost:1225/shows

###

GET http://localhost:1225/play/christmas_eve_sarajevo

###

GET http://localhost:1225/play/asdf

###

GET http://localhost:1225/static

###

GET http://localhost:1225/next
